# Generated by Django 5.1.7 on 2025-05-16 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contactos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Endereço de Email"),
                ),
                (
                    "assunto",
                    models.CharField(
                        max_length=100, verbose_name="Assunto da Mensagem"
                    ),
                ),
                ("mensagem", models.TextField(verbose_name="Conteúdo da Mensagem")),
                (
                    "ano",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Ano (se aplicável)",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Categoria (se aplicável)",
                    ),
                ),
                (
                    "curso",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Curso (se aplicável)",
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Data de Envio",
                    ),
                ),
                (
                    "lido",
                    models.BooleanField(default=False, verbose_name="Mensagem Lida"),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Contacto",
                "verbose_name_plural": "Mensagens de Contacto",
                "db_table": "contactos",
                "ordering": ["-data_envio"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Eventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=128)),
                ("data", models.DateField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, max_length=256, null=True)),
                ("texto", models.TextField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos_imgs/"),
                ),
                ("visivel", models.IntegerField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("is_hidden", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "eventos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("apelido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "data_subscricao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subscrição de Newsletter",
                "verbose_name_plural": "Subscrições de Newsletter",
                "db_table": "newsletter",
                "ordering": ["-data_subscricao"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, default="", max_length=250)),
                ("mensagem", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.eventos",
                    ),
                ),
            ],
            options={
                "db_table": "comentarios",
                "ordering": ["-created"],
            },
        ),
    ]
