# Generated by Django 5.1.6 on 2025-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventoid", models.PositiveIntegerField(db_column="eventoId")),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("mensagem", models.TextField()),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "comentarios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Contactos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("ano", models.CharField(blank=True, max_length=255, null=True)),
                ("categoria", models.CharField(blank=True, max_length=255, null=True)),
                ("curso", models.CharField(blank=True, max_length=255, null=True)),
                ("assunto", models.CharField(blank=True, max_length=255, null=True)),
                ("mensagem", models.TextField(blank=True, null=True)),
                ("data_envio", models.DateTimeField()),
            ],
            options={
                "db_table": "contactos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Eventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=128)),
                ("data", models.DateField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, max_length=256, null=True)),
                ("texto", models.TextField(blank=True, null=True)),
                ("imagem", models.CharField(blank=True, max_length=128, null=True)),
                ("visivel", models.IntegerField(blank=True, null=True)),
                ("eventbrite_code", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "eventos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(db_collation="latin1_swedish_ci", max_length=30),
                ),
                (
                    "apelido",
                    models.CharField(db_collation="latin1_swedish_ci", max_length=30),
                ),
                (
                    "email",
                    models.CharField(db_collation="latin1_swedish_ci", max_length=250),
                ),
            ],
            options={
                "db_table": "newsletter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
