# Generated by Django 5.1.7 on 2025-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("url", models.URLField(unique=True, verbose_name="Ligação")),
                ("summary", models.TextField(blank=True, verbose_name="Resumo")),
                ("published", models.DateTimeField(verbose_name="Data de publicação")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Visível no site público"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
                "ordering": ["-published"],
            },
        ),
    ]
