# Generated by Django 5.1.6 on 2025-03-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={},
        ),
    ]
