# Generated by Django 5.1.7 on 2025-05-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_newsarticle_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["-published"], name="dashboard_n_publish_5e8710_idx"
            ),
        ),
    ]
