# Generated by Django 5.1.6 on 2025-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_newsletter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
