# Generated by Django 5.1.7 on 2025-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_newsarticle_dashboard_n_publish_5e8710_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Data de nascimento")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telemóvel"
                    ),
                ),
                (
                    "study_cycle",
                    models.CharField(max_length=100, verbose_name="Ciclo de estudos"),
                ),
                ("course", models.CharField(max_length=255, verbose_name="Curso")),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                ("interests", models.TextField(blank=True, verbose_name="Interesses")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membro",
                "verbose_name_plural": "Membros",
                "ordering": ["full_name"],
            },
        ),
    ]
