# Generated by Django 5.1.7 on 2025-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_membro"),
    ]

    operations = [
        migrations.AddField(
            model_name="membro",
            name="status",
            field=models.CharField(
                choices=[("atual", "Membro atual"), ("ex", "Ex-membro")],
                default="atual",
                max_length=5,
                verbose_name="Estado",
            ),
        ),
    ]
