# Generated by Django 5.1.6 on 2025-03-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_newsletter_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventos",
            options={},
        ),
    ]
