# Generated by Django 5.1.7 on 2025-06-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_membro_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField()),
                (
                    "template_image",
                    models.ImageField(upload_to="certificates/templates/"),
                ),
                ("font_file", models.FileField(upload_to="certificates/fonts/")),
                ("font_size", models.PositiveIntegerField(default=120)),
                (
                    "name_x",
                    models.PositiveIntegerField(help_text="Posição X (centro) do nome"),
                ),
                (
                    "name_y",
                    models.PositiveIntegerField(help_text="Posição Y (centro) do nome"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CertificateIssued",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField()),
                ("participant_name", models.CharField(max_length=255)),
                ("participant_email", models.EmailField(blank=True, max_length=254)),
                (
                    "certificate_file",
                    models.FileField(upload_to="certificates/issued/"),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("event_id", "participant_name")},
            },
        ),
    ]
