# Generated by Django 5.1.6 on 2025-03-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_eventos_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventos",
            name="eventbrite_code",
        ),
    ]
