# Generated by Django 5.1.7 on 2025-06-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_certificatetemplate_certificateissued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="font_file",
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="font_size",
            field=models.PositiveIntegerField(default=67),
        ),
    ]
