# Generated by Django 5.1.6 on 2025-03-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_customuser_delete_user_alter_eventos_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
