# Generated by Django 5.1.6 on 2025-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventos",
            name="local",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
