# Generated by Django 5.1.7 on 2025-06-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventos",
            name="seo_descricao",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="eventos",
            name="seo_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="eventos",
            name="seo_texto",
            field=models.TextField(blank=True, null=True),
        ),
    ]
