# Generated by Django 5.1.7 on 2025-05-13 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_eventos_local"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "managed": True,
                "ordering": ["-data_subscricao"],
                "verbose_name": "Subscrição de Newsletter",
                "verbose_name_plural": "Subscrições de Newsletter",
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="data_subscricao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="apelido",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
