# Generated by Django 5.1.7 on 2025-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_eventos_seo_descricao_eventos_seo_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="ISACA PDI", max_length=120, verbose_name="Nome do site"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Em manutenção?"),
                ),
                (
                    "maintenance_message",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: «Voltamos já! Só estamos a aplicar uma atualização.»",
                        max_length=180,
                        verbose_name="Mensagem de manutenção",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Definições do site",
            },
        ),
    ]
