# Generated by Django 5.1.7 on 2025-05-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_newsletter_options_newsletter_ativo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactos",
            options={
                "managed": True,
                "ordering": ["-data_envio"],
                "verbose_name": "Mensagem de Contacto",
                "verbose_name_plural": "Mensagens de Contacto",
            },
        ),
    ]
