# Generated by Django 5.1.7 on 2025-05-15 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_contactos_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comentarios",
        ),
        migrations.RemoveField(
            model_name="eventos",
            name="local",
        ),
        migrations.AddField(
            model_name="contactos",
            name="lido",
            field=models.BooleanField(default=False, verbose_name="Mensagem Lida"),
        ),
        migrations.AddField(
            model_name="eventos",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventos",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="contactos",
            name="ano",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Ano (se aplicável)"
            ),
        ),
        migrations.AlterField(
            model_name="contactos",
            name="assunto",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Assunto da Mensagem"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactos",
            name="categoria",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Categoria (se aplicável)",
            ),
        ),
        migrations.AlterField(
            model_name="contactos",
            name="curso",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Curso (se aplicável)",
            ),
        ),
        migrations.AlterField(
            model_name="contactos",
            name="data_envio",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Data de Envio",
            ),
        ),
        migrations.AlterField(
            model_name="contactos",
            name="email",
            field=models.EmailField(
                default="Assunto não especificado",
                max_length=254,
                verbose_name="Endereço de Email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactos",
            name="mensagem",
            field=models.TextField(
                default="mensaegem não especificado",
                verbose_name="Conteúdo da Mensagem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactos",
            name="nome",
            field=models.CharField(
                default="nome", max_length=100, verbose_name="Nome Completo"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventos",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="eventos_imgs/"),
        ),
        migrations.AlterModelTable(
            name="contactos",
            table="dashboard_contactos_mensagens",
        ),
    ]
